### ISSUE TITLE
setup-erlang github action proposal

### ISSUE THREAD

**Issue by starbelly** [erlef/build-and-packaging-wg#12]
## Background

We recently adopted the setup-elixir github action. It may make sense to have a setup-erlang action to go with it. Currently and as far as I know there are two setup-erlang actions in the wild: 

- https://github.com/gleam-lang/setup-erlang

- https://github.com/bajankristof/setup-erlang

I believe it makes sense to not only have a setup-erlang action within the erlef, but that it's important that both pull sources from the same place and provide the same argument interface. 

Note: That one key difference between setup-elixir and gleam's setup-erlang is that the latter supports windows. It may be we don't want to take on this burden yet unless we have someone who is willing to help test and maintain. 

## Objective(s)

- [ ] create an erlef/setup-erlang action based off setup-elixir

**Comment by starbelly** [comment]
Note: That I'm highly interested in @lpil thinks of this.

**Comment by tsloughter** [comment]
Should definitely keep Windows. rebar3 tests against windows but currently just uses `choco install erlang` to do so.

**Comment by starbelly** [comment]
> Should definitely keep Windows. rebar3 tests against windows but currently just uses `choco install erlang` to do so.

Yeah, I think that's very useful, and more and more people are using windows for elixir as well. I would just at least a few in the group to be on board with maintaining it all.

**Comment by lpil** [comment]
I don't really know much about the Windows code as it contributed to the project and I don't speak powershell. It has worked well so far though! I've not had any problems coming from Windows.

**Comment by starbelly** [comment]
@lpil I also wanted to hear your thoughts in general as the erlef should support the community, not dominate it, I assume by your feedback above you have no problems with this moving forward?

**Comment by ferd** [comment]
Skipped this one from the last meeting since @starbelly wasn't around, will bring it up on the next one?

**Comment by starbelly** [comment]
Closing this per discussion today and the action item created #20
