### ISSUE TITLE
Hex Web Auth Flow

### ISSUE THREAD

**Issue by starbelly** [erlef/build-and-packaging-wg#18]
## Background

We have discussed in various issues moving to a "web auth flow" for authenticating with mix and rebar3 hex. I would like for the group to over the flow, discuss the pros and cons, and to formulate a time line if possible for moving to this. One big looming question for myself is : Will we all together stop password auth or will it be optional? This discussion is also in prep for completing the tasks in #11 

## Objective(s)

 - [ ] Create an issue describing the approach, pros/cons, and strategy/timeline
 - [ ] Enumerate that tasks that must be completed in order to start work on web auth 
 - [ ] Enumerate the tasks that must be completed to implement web auth flow.

**Comment by josevalim** [comment]
Perhaps this could be a project for Google Summer of Code? Implementation wise it is a matter of implementing the relevant Hex APIs and then invoking them from the client. :)

**Comment by starbelly** [comment]
@josevalim I think that's a great idea. I'll be a mentor on gsoc so :)

**Comment by pablocostass** [comment]
I agree, this could be a neat proposal for GSoC. I was about to create an agenda item to discuss proposals within the WG, so it's great to already have one idea :)

**Comment by starbelly** [comment]
Closed per today's discussion and #21
