### ISSUE TITLE
Retire build and packaging channel on erlanger

### ISSUE THREAD

**Issue by starbelly** [erlef/build-and-packaging-wg#28]
# Background 

Per #23 we have decided to close the build and packaging channel on erlanger. It was decided to leave a note in the channel (in the form of an updated topic and description) for one month, then close the channel completely. 

# Tasks

The following tasks must be completed to resolve this issue. 

- [x] Set a topic and description on the channel on erlanger to inform others that the official channel is on eef slack. 
- [x] On May the 4th the channel is to be closed. 

# Related agenda items, issues, and pull requests. 

 - #23

**Comment by paulo-ferraz-oliveira** [comment]
First one's done. Now, does GitHub have reminders?

**Comment by paulo-ferraz-oliveira** [comment]
> Now, does GitHub have reminders?

Hm. I was kidding but found some sort of native integration with Slack, and then remembered that Slack has reminders... 😄

**Comment by starbelly** [comment]
May the 4th be with you!
