### ISSUE TITLE
Moving rebar_mix to erlef

### ISSUE THREAD

**Issue by starbelly** [erlef/build-and-packaging-wg#29]
## Background

In line with a few other things that have been taken on by the foundation, namely rebar3_hex and setup-beam (formerly setup-elixir) I propose that we also take on rebar_mix. 

More and more erlangers and other BEAM users are wanting to leverage elixir dependencies. Currently rebar_mix lives at https://github.com/Supersonido/rebar_mix and owned by @tsloughter. 

I think it would be good for the community and the foundation to adopt this plugin if @tsloughter agrees. 

The alternative is moving it to another namespace or simply adding more maintainers to the existing repo. 

I made an example repo the other day and shared it with some erlangers and a few were surprised it was possible and even easy. However, I also had to to use in my example the master branch of the git repository to make this fully work (as intended) as a release of rebar_mix hasn't been done in some time, yet a fix for protocol consolidation lives in master. The burden of maintaining this plugin should be a shared responsibility IMO. 

In case I am not able to make it to the next meeting my order of preference is listed in the potential action items below. 

## Objective(s)

- Discuss and get consensus on said issue
- Potential action items : 
   1. Move it to erlef
   2. Move it another namespace/org on github
   3. Add more maintainers to the existing repo on github.

**Comment by ferd** [comment]
We might want to ask @Supersonido as well since they're the current most active maintainer.

**Comment by starbelly** [comment]
@ferd Ahh, I didn't know that. I had made an assumption I suppose that this was handed over to tristan. Thanks for clarifying.

**Comment by tsloughter** [comment]
Yea, na, it was mine and then I handed it over to @Supersonido

**Comment by starbelly** [comment]
@tsloughter 😁

**Comment by ferd** [comment]
We discussed another option:
- asking @supersonido for the releases, optionally offering adding one of the WG folks to have the right to publish releases
- if we get no traction, then possibly fork and bring in

**Comment by starbelly** [comment]
As discussed, I will open up an issue and try other channels to communicate with maintainers of rebar_mix as preferably it lives there and possibly more maintainers get added to distribute the load. Will leave this agenda item open until this is considered resolved.

**Comment by paulo-ferraz-oliveira** [comment]
If we fork it, could reconsider calling it `rebar3_mix`?

**Comment by Supersonido** [comment]
I have no problem handling the releases. I have been very busy between studies and my current job. I just put in master but I think I don't have permissions to get it in hex.pm

**Comment by starbelly** [comment]
At this point, I would suggest a hard fork. Maybe this issue isn't as pressing as I think it is, but it seems like every week someone on erlanger is trying to use elixir deps in a rebar project and they can not (rebar_mix is linked in rebar3 docs as FYI). 

This kind of interop is a huge reason this group and foundation exist and I don't think it makes any sense to keep it stalled. I don't want to step on toes, but I do want to get this issue resolved and be able to point people to a simple plugin that compiles elixir dependencies. 

@tsloughter Thoughts?

**Comment by tsloughter** [comment]
Huh, why a fork?

I have ownership on the hex package so I can give you permission to publish @starbelly

**Comment by starbelly** [comment]
@tsloughter Yeah, I mean I guess that isn't needed. I wasn't sure if you wanted to let development ensue as is on that repo. Basically, what IMO needs to happen is we need to reset back to https://github.com/Supersonido/rebar_mix/commit/30b5504d49965ca165a32751afd87a04fd5a7971 which would clobber all changes after that. 

What are your thoughts on where the github repo lives @tsloughter ? My original suggestion was to move it to erlef, some didn't agree with that per concerns of turning into the apache foundation.

**Comment by starbelly** [comment]
Closing this as resolved. 

To note, @tsloughter pointed out that mix.exs in an elixir project must be parsed as rebar3 will only fetch top level deps (i.e., if I specify dep A which is an elixir dep, and it depends on B and C which are also elixir deps, only dep A shall be fetched). There are other issues aside from that main one. Thus, rebar_mix must handle more than simply compilation.
