### ISSUE TITLE
Doc module attributes

### ISSUE THREAD

**Issue by josevalim** [erlef/build-and-packaging-wg#32]
I have written an EEP draft for new doc attributes in Erlang/OTP: https://docs.google.com/document/d/1HzdwIQYww1zCwqr0MSUAc5cYB9bgnpFXiRAtmqK3S4Y/edit

The idea is to submit it as an EEP once Erlang/OTP 24 is out. Depending on the feedback, we will know if we should focus on improving EDoc or if there is a general interest in a more integrated documentation format.

**Comment by paulo-ferraz-oliveira** [comment]
Would `-moduledoc(...)` also be allowed, with the parenthesis? (I'm not sure this isn't already part of the parser/compiler). Same goes for `-doc`.

**Comment by paulo-ferraz-oliveira** [comment]
How do you propose documenting parameters? Or is it outside the scope of your proposal?

**Comment by paulo-ferraz-oliveira** [comment]
Would it be acceptable to also represent the equivalent of "@throws" (for which`-spec(_)`ing as `no_return()` is no good)?

**Comment by paulo-ferraz-oliveira** [comment]
And what about `@private`'s equivalent?

**Comment by michalmuskala** [comment]
> Would -moduledoc(...) also be allowed, with the parenthesis? (I'm not sure this isn't already part of the parser/compiler). Same goes for -doc.

The erlang grammar has optional parentheses on all attributes (e.g. `-module foo.` is perfectly valid). Whether some are used with them or without seems more like a general community preference than a hard rule.

**Comment by paulo-ferraz-oliveira** [comment]
I read the whole document and left a couple of comments. Very nice stuff!

Some questions remain:
1. how do you propose documenting parameters? Or is it outside the scope of your proposal?
2. would it be acceptable to also represent the equivalent of "@throws" (for which`-spec(_)`ing as `no_return()` is no good)?

**Comment by josevalim** [comment]
> how do you propose documenting parameters? Or is it outside the scope of your proposal?

You can document the parameters with text. There is no structured documentation (or rather, I would say the structured documentation for params happens via typespecs).

Similarly, I think `@throws` starts venturing into typespecs, especially because you will use types to document it. I believe it is outside of the scope of this proposal.

**Comment by paulo-ferraz-oliveira** [comment]
> You can document the parameters with text. There is no structured documentation (or rather, I would say the structured documentation for params happens via typespecs).

Sure, understood. I was thinking about stuff like `@param Name this is the name of the resource to change`.
