### ISSUE TITLE
begin license normalization on rebar and hex

### ISSUE THREAD

**Issue by supersimple** [erlef/build-and-packaging-wg#34]
## Background
We ask for licenses when publishing packages, but we never validate them. Therefore, the license can be nondescript or ambiguous.

## Objective(s)
Develop an erlang library/module that can be vendored into hex and rebar that checks licenses against the SPDX list.
see:https://github.com/hexpm/hex/pull/886

**Comment by supersimple** [comment]
- do not prevent publishing if license is not recognized by sdpx - warn only
- find or create tool to verify licenses on a project (validate they are all compatible.)
- make licenses linkable/searchable on hex.pm

**Comment by supersimple** [comment]
@supersimple will work with @tsloughter on writing the Erlang module

**Comment by ferd** [comment]
This has been discussed in the last meeting. Work is ongoing; The mix stuff handles it already, rebar3_hex v7 deals with the warning, and there's an open issue for Gleam linked here. CLosing this as discussed and handled.
