### ISSUE TITLE
Rebar3 vendoring/offline builds update

### ISSUE THREAD

**Issue by ferd** [erlef/build-and-packaging-wg#48]
## Background

This has been an ongoing issue. We just merged an initial vendoring provider (PR: https://github.com/erlang/rebar3/pull/2689) that's experimental and unstable.

While this doesn't explicitly help Ericsson right now, it unblocks some of the structuring work on Rebar3's end:

- [x] Only umbrella projects being vendored
- [x] A path towards in-repo plugins (in umbrellas only)
- [x] A possible way to structure rebar3 itself in a way that is friendly with vendoring for 3rd party package managers
- [x] more precise scoping of network call prevention/interruption
   - [x] we're still vague on forms of error handling there, but maybe it won't be that bad.

Global plugins are still an unanswered question, because their evaluation is done before any project-specific setting.

## Objective(s)

Description or task list of actionable item(s) that must be fulfilled to resolve the issue. 
Leave the section with a TBD comment if objectives are not known at the time of creation.

**Comment by starbelly** [comment]
All these tasks have been complete, should this still be open?

**Comment by ferd** [comment]
I just need to cut a release at this point

**Comment by zuiderkwast** [comment]
In Ericsson's products, they're still interested in a release. It seems the won't update rebar3 without a release.

**Comment by ferd** [comment]
sorry, work's been hectic, I'll try to get it done in the upcoming days
